### ISSUE TITLE
The getSimilar Method Not Passing Parameters

### ISSUE THREAD

**Issue by nholdren** [bshaffer/php-echonest-api#4]
The getSimilar() method in the Artist class does not pass the parameters for the request. Should be:

$response = $this->getForArtist('artist/similar', array(
      'results'         => $results,
      'start'           => $start,
      'bucket'          => $bucket,
      'max_familiarity' => $max_familiarity,
      'min_familiarity' => $min_familiarity,
      'max_hotttnesss'  => $max_hotttness,
      'min_hotttnesss'  => $min_hotttness,
      'reverse'         => $reverse,
      'limit'           => $limit,
      'seed_catalog'    => $seed_catalog
    ));

**Comment by bshaffer** [comment]
This has been fixed in 221891e3d9a2c9ec1a5e92c9e6c842ea1f92e783

Thank you for finding this.  As you already did all the hard work, consider forking this repository and [submitting pull requests](http://help.github.com/pull-requests/) in the future.  It really is the best way to contribute.

Thanks again!
